# Generated by Django 4.2.13 on 2024-06-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name_plural': 'trabajadores'},
        ),
    ]
